name: generate animation

on:
  # Schedule the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
  
  # Allows manual triggering of the workflow
  workflow_dispatch:
  
  # Trigger on push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Generate the GitHub contribution grid snake SVG animation
      - name: Generate GitHub contribution grid snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the generated SVG to the output branch
      - name: Push GitHub contribution grid snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
