name: Generate Snake Contribution Graph

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:  # Allows manual triggering from the Actions tab

# The sequence of runs in this workflow
jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner to execute the job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Generate the snake contribution graph
      - name: Generate Snake Graph
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: CodderPrince  # Replace with your GitHub username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 3: Check the git status for debugging purposes
      - name: Check git status
        run: git status

      # Step 4: Push the generated snake graph to the repository
      - name: Push generated files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master  # Push to the main branch
          force: true

      # Step 5: Deploy the snake graph to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Output branch for GitHub Pages
          build_dir: dist        # Directory with the generated snake graph
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
